import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {parseCase,project,catalog,plan,setStatus} from '../cases/catalog.mjs';import {start} from '../execution/runner.mjs';import {record,recover} from '../record_store/store.mjs';import {inside} from '../lib/paths.mjs';
function fixture(){const repo=fs.mkdtempSync(path.join(os.tmpdir(),'regression-'));fs.mkdirSync(path.join(repo,'cases'));fs.writeFileSync(path.join(repo,'index.yaml'),'schemaVersion: 1\ncaseDirectories: [cases]\nregressionDirectory: runs\n');const script=(id,status='active',body="ctx.assert('real assertion',true,true)")=>`globalThis.notExecuted=true;export const USECASE={name:'Case ${id}',description:'Precondition, actions, expected'};export const META={id:'${id}',module:'sample',surface:'integration',priority:'critical',origin:'requirement',status:'${status}',statusReason:'fixture',covers:[],requires:[],effects:'read-only',cost:'fast'};export async function run(ctx){${body}}`;fs.writeFileSync(path.join(repo,'cases/one.mjs'),script('one'));return {repo,p:project(repo,'index.yaml'),script,close:()=>fs.rmSync(repo,{recursive:true,force:true})};}
test('AST discovery never executes scripts and rejects computed metadata',()=>{const f=fixture();try{assert.equal(catalog(f.p).cases.length,1);assert.equal(globalThis.notExecuted,undefined);assert.throws(()=>parseCase(f.script('x').replace("name:'Case x'","name:process.exit()"),'x'),/literal/);fs.writeFileSync(path.join(f.repo,'cases/two.mjs'),f.script('one'));assert.equal(catalog(f.p).diagnostics.length,1);}finally{f.close();}});
test('inactive selection requires explicit validation and source status changes stay literal',()=>{const f=fixture();try{setStatus(f.p,'one','rotten','Verified false positive');assert.equal(plan(f.p).selected,0);assert.equal(plan(f.p,{ids:'one',validateInactive:true}).selected,1);assert.equal(plan(f.p,{profile:'change'}).selected,0);}finally{f.close();}});
test('worker stores evaluated assertions, failure and telemetry-independent timing',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/two.mjs'),f.script('two','active',"ctx.assert('mismatch',false,true)"));const r=await start(f.p,{}).completion;assert.equal(r.counts.passed,1);assert.equal(r.counts.failed,1);assert.equal(record(f.p,r.id).cases.find(c=>c.id==='two').assertions[0].passed,false);assert.equal(fs.existsSync(path.join(f.p.recordRoot,r.id,'scripts')),false);}finally{f.close();}});
test('blocking prerequisites are non-green and symlink traversal is rejected',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one').replace("requires:[]","requires:['identity']"));const r=await start(f.p,{}).completion;assert.equal(r.counts.blocked,1);fs.symlinkSync(os.tmpdir(),path.join(f.repo,'escape'));assert.throws(()=>inside(f.repo,'escape/missing/new'),/Symlink/);}finally{f.close();}});
test('missing provider telemetry is inconclusive and cannot pass',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one','active',"await ctx.performance('Actual business latency',{traceId:'example',maximumMs:50})"));const r=await start(f.p,{}).completion;assert.equal(r.counts.blocked,1);assert.equal(r.cases[0].assertions[0].state,'inconclusive');}finally{f.close();}});
test('timeout terminates worker and remains an error',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one','active',"await new Promise(()=>{})"));const r=await start(f.p,{timeoutMs:50}).completion;assert.equal(r.counts.error,1);assert.equal(r.cases[0].error,'Case timeout');}finally{f.close();}});
test('metadata selection intersects fields, unions alternatives and matches array members without bypassing lifecycle',async()=>{
 const f=fixture();try{
  fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one').replace('covers:[]',"covers:['messages.send']").replace("cost:'fast'","cost:'slow'"));
  fs.writeFileSync(path.join(f.repo,'cases/two.mjs'),f.script('two').replace("priority:'critical'","priority:'normal'"));
  assert.equal(plan(f.p,{meta:{priority:['critical','normal'],cost:['slow']}}).items.filter(c=>c.selected)[0].id,'one');
  assert.equal(plan(f.p,{meta:JSON.stringify({covers:['messages.send'],surface:['integration']})}).selected,1);
  assert.equal(plan(f.p,{meta:{origin:['bug']}}).selected,0);
  assert.throws(()=>plan(f.p,{meta:{prioritty:['critical']}}),/Unknown metadata/);
  assert.throws(()=>plan(f.p,{meta:null}),/object/);
  setStatus(f.p,'one','rotten','Verified fixture repair');
  assert.equal(plan(f.p,{meta:{id:['one'],status:['rotten']}}).selected,0);
  assert.equal(plan(f.p,{meta:{id:['one'],status:['rotten']},validateInactive:'true'}).selected,1);
  assert.equal(plan(f.p,{meta:{id:['one']},validateInactive:'false'}).selected,0);
  setStatus(f.p,'one','obsolete','Feature removed');
  assert.equal(plan(f.p,{meta:{id:['one']},validateInactive:true}).selected,0);
 }finally{f.close();}
});
test('agent prompt uses the consumer instruction verbatim and carries the same selection; false write authorization stays blocked',async()=>{
 const f=fixture();try{
  const {service}=await import('../lib/service.mjs');
  const meta={module:['sample'],surface:['integration'],priority:['critical']};
  const expected=plan(f.p,{meta});const prompt=await service(f.p,'agent_prompt',{meta});
  const skill=fs.readFileSync(new URL('../SKILL.md',import.meta.url),'utf8');const instruction=skill.match(/## Run regression\n([\s\S]*?)(?=\n## |$)/)[1].trim();
  assert.equal(prompt.instruction,instruction);assert.equal(prompt.selected,expected.selected);assert.deepEqual(prompt.filters.meta,meta);assert.ok(prompt.prompt.includes(f.repo));
  const dimensions=await service(f.p,'filter_options');assert.ok(dimensions.some(d=>d.key==='priority'&&d.values.includes('critical')));
  fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one').replace("effects:'read-only'","effects:'external-write'"));
  const run=await start(f.p,{allowExternalWrites:'false'}).completion;assert.equal(run.counts.blocked,1);
 }finally{f.close();}
});
test('case-only drafts are discoverable but cannot execute, even with explicit IDs',()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/draft.mjs'),f.script('draft').replace(/export async function run\(ctx\)\{.*\}$/,''));const c=catalog(f.p);assert.equal(c.diagnostics.length,0);assert.equal(c.cases.find(c=>c.id==='draft').runnable,false);const p=plan(f.p,{ids:'draft'});assert.equal(p.selected,0);assert.equal(p.items.find(c=>c.id==='draft').reason,'Script not implemented');assert.throws(()=>start(f.p,{ids:'draft'}),/No selected cases/);}finally{f.close();}});
test('Module ancestors are derived and select descendants at segment boundaries across all scopes',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one').replace("module:'sample'","module:'context/files/reading'").replace("priority:'critical'","priority:'normal'"));fs.writeFileSync(path.join(f.repo,'cases/two.mjs'),f.script('two').replace("module:'sample'","module:'contextual/files'"));for(const filters of [{modules:'context'},{meta:{module:['context']}},{profile:'change',changedModules:'context'},{profile:'release',changedModules:'context',modules:'context'}])assert.deepEqual(plan(f.p,filters).items.filter(c=>c.selected).map(c=>c.id),['one']);const {filterOptions}=await import('../cases/filters.mjs');assert.ok(filterOptions(catalog(f.p).cases).find(d=>d.key==='module').values.includes('context/files'));assert.throws(()=>parseCase(f.script('bad').replace("module:'sample'","module:'context//files'"),'bad'),/id\/module/);}finally{f.close();}});
test('environment bindings are consumed by scripts, captured in records and blocked before execution when unavailable',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'adapter.mjs'),`export async function resolve({parameters}){return {agent:{id:parameters.agent}};}export async function check({resources}){return [{ready:resources.agent.id==='online',reason:'Agent offline'}];}`);fs.writeFileSync(path.join(f.repo,'env.yaml'),'parameters:\n  agent: offline\n');fs.appendFileSync(path.join(f.repo,'index.yaml'),'environment:\n  default: local\n  adapter: adapter.mjs\n  profiles:\n    local: env.yaml\n');const p=project(f.repo,'index.yaml');fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one','active',"ctx.assert('resolved agent',ctx.resources.agent.id,'online')")+"\nexport const REQUIREMENTS={agent:{state:'online'}};");const blocked=await start(p,{}).completion;assert.equal(blocked.counts.blocked,1);assert.equal(blocked.cases[0].assertions,undefined);const passed=await start(p,{params:'{"agent":"online"}'}).completion;assert.equal(passed.counts.passed,1);assert.equal(passed.environment.resources.agent.id,'online');assert.equal(passed.cases[0].preflight.resources.agent.id,'online');const {service}=await import('../lib/service.mjs');await assert.rejects(()=>service(p,'environment',{params:'{"token":"forbidden"}'}),/Credentials/);}finally{f.close();}});
test('commands receive stdin without persisting sensitive output when capture is disabled',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one','active',`const r=await ctx.command('private input',process.execPath,['-e',"process.stdin.pipe(process.stdout)"],{input:'private-fixture-value',capture:false});ctx.assert('stdin reached process',r.stdout==='private-fixture-value',true);`));const r=await start(f.p,{}).completion;assert.equal(r.counts.passed,1);assert.equal(r.cases[0].outputs,undefined);assert.ok(!JSON.stringify(r).includes('private-fixture-value'));}finally{f.close();}});
test('functional assertions compare structured snapshots by value and retain meaningful mismatches',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one','active',"ctx.assert('equivalent snapshot',{versions:['1','2'],installed:true},{versions:['1','2'],installed:true})"));fs.writeFileSync(path.join(f.repo,'cases/two.mjs'),f.script('two','active',"ctx.assert('changed snapshot',{versions:['1','3']},{versions:['1','2']})"));const r=await start(f.p,{}).completion;assert.equal(r.counts.passed,1);assert.equal(r.counts.failed,1);assert.deepEqual(r.cases.find(c=>c.id==='two').assertions[0].actual,{versions:['1','3']});}finally{f.close();}});
test('case timeout stops the owned command process tree instead of leaving background writes',async()=>{const f=fixture();try{const body=`await ctx.command('owned delayed write',process.execPath,['-e',"const fs=require('node:fs');fs.writeFileSync(process.argv[1],'ready');setTimeout(()=>fs.writeFileSync(process.argv[2],'leaked'),2000)",ctx.repo+'/ready',ctx.repo+'/leaked']);ctx.assert('command returned',true,true);`;fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one','active',body));const r=await start(f.p,{timeoutMs:1200}).completion;assert.equal(r.counts.error,1);assert.equal(fs.existsSync(path.join(f.repo,'ready')),true);await new Promise(resolve=>setTimeout(resolve,1500));assert.equal(fs.existsSync(path.join(f.repo,'leaked')),false);}finally{f.close();}});
test('a scoped repair creates a second round without overwriting its failed predecessor',async()=>{const f=fixture();try{fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one','active',"ctx.assert('mismatch',false,true)"));fs.writeFileSync(path.join(f.repo,'cases/two.mjs'),f.script('two'));const first=await start(f.p,{}).completion;fs.writeFileSync(path.join(f.repo,'cases/one.mjs'),f.script('one'));const second=await start(f.p,{runId:first.id,ids:'one'}).completion;assert.equal(second.runId,first.id);assert.equal(second.roundNumber,2);assert.equal(second.cases.find(c=>c.id==='two').status,'excluded');assert.equal(record(f.p,first.id).cases.find(c=>c.id==='one').status,'failed');assert.equal(second.counts.passed,1);assert.throws(()=>start(f.p,{runId:'bad'}),/Invalid run/);}finally{f.close();}});

test('trial cases run by default and remain trial after green execution',async()=>{const f=fixture();try{setStatus(f.p,'one','trial','First implementation');assert.equal(plan(f.p).selected,1);assert.equal(plan(f.p,{meta:{status:['trial','active']}}).selected,1);const r=await start(f.p,{}).completion;assert.equal(r.counts.passed,1);assert.equal(catalog(f.p).cases[0].meta.status,'trial');setStatus(f.p,'one','active','Reviewed execution and cleanup in '+r.id);assert.equal(catalog(f.p).cases[0].meta.status,'active');}finally{f.close();}});
