import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {schedule,caseLocks} from '../execution/scheduler.mjs';import {start,cancel} from '../execution/runner.mjs';import {project,plan} from '../cases/catalog.mjs';
const pause=ms=>new Promise(r=>setTimeout(r,ms));
test('bounded scheduling overlaps independent cases and serializes resource conflicts and exclusive barriers',async()=>{
 const cases=[{id:'a',meta:{parallelSafe:true,locks:['actor']}},{id:'b',meta:{parallelSafe:true,locks:['actor']}},{id:'c',meta:{parallelSafe:true}},{id:'d',meta:{}},{id:'e',meta:{parallelSafe:true}}];const active=new Set(),overlaps=[];let peak=0;
 await schedule(cases,2,caseLocks,async c=>{for(const other of active)overlaps.push([other,c.id]);active.add(c.id);peak=Math.max(peak,active.size);await pause(20);active.delete(c.id);});
 assert.equal(peak,2);assert.ok(overlaps.some(x=>x.includes('a')&&x.includes('c')));assert.ok(!overlaps.some(x=>x.includes('a')&&x.includes('b')));assert.ok(!overlaps.some(x=>x.includes('d')));assert.deepEqual(caseLocks({meta:{parallelSafe:true,surface:'gui'}}),[]);
});
function fixture(body){const repo=fs.mkdtempSync(path.join(os.tmpdir(),'trace-parallel-'));fs.mkdirSync(path.join(repo,'cases'));fs.writeFileSync(path.join(repo,'index.yaml'),'schemaVersion: 1\ncaseDirectories: [cases]\nregressionDirectory: runs\n');for(const id of ['a','b','c'])fs.writeFileSync(path.join(repo,'cases',id+'.mjs'),`export const USECASE={name:'${id}',description:'Independent worker'};export const META={id:'${id}',module:'sample',surface:'integration',priority:'normal',origin:'requirement',status:'trial',effects:'read-only',cost:'fast',parallelSafe:true};export async function run(ctx){${body}}`);return {repo,p:project(repo,'index.yaml')};}
test('parallel workers retain independent assertions, files and overlapping start/end evidence',async()=>{const f=fixture("await new Promise(r=>setTimeout(r,400));ctx.assert(ctx.caseId,ctx.caseId,ctx.caseId)");try{const run=await start(f.p,{concurrency:2}).completion;assert.equal(run.counts.passed,3);const [a,b,c]=run.cases;assert.ok(Date.parse(a.startedAt)<Date.parse(b.finishedAt)&&Date.parse(b.startedAt)<Date.parse(a.finishedAt));assert.ok(Date.parse(c.startedAt)>=Math.min(Date.parse(a.finishedAt),Date.parse(b.finishedAt)));for(const item of run.cases)assert.equal(item.assertions[0].name,item.id);assert.ok(!fs.readdirSync(path.join(f.p.recordRoot,run.id)).some(n=>n.includes('worker-')));assert.throws(()=>plan(f.p,{concurrency:0}),/concurrency/);assert.throws(()=>plan(f.p,{concurrency:9}),/concurrency/);}finally{fs.rmSync(f.repo,{recursive:true,force:true});}});
test('cancel stops every parallel worker and excludes pending execution',async()=>{const f=fixture("ctx.assert('started',true,true);for(;;)await new Promise(r=>setTimeout(r,100))");try{const job=start(f.p,{concurrency:2});await pause(500);cancel(job.id);const run=await job.completion;assert.equal(run.state,'cancelled');assert.equal(run.counts.cancelled,3);}finally{fs.rmSync(f.repo,{recursive:true,force:true});}});

test('shared readers overlap, writers exclude all accesses and maturity does not serialize trial cases',async()=>{const items=[{id:'a',meta:{status:'trial',locks:['read:document']}},{id:'b',meta:{status:'active',locks:['read:document']}},{id:'c',meta:{status:'trial',locks:['write:document']}}];const active=new Set(),overlaps=[];await schedule(items,3,caseLocks,async c=>{for(const id of active)overlaps.push([id,c.id]);active.add(c.id);await pause(20);active.delete(c.id);});assert.deepEqual(overlaps,[['a','b']]);});
