import fs from 'node:fs';import path from 'node:path';import YAML from 'yaml';import {inside} from '../lib/paths.mjs';
export function save(p,record){const dir=inside(p.repo,path.relative(p.repo,path.join(p.recordRoot,record.id)));fs.mkdirSync(dir,{recursive:true});const f=path.join(dir,'regression.yaml'),tmp=f+'.tmp';fs.writeFileSync(tmp,YAML.stringify(record),{mode:0o600});const stamp=signature(tmp);fs.renameSync(tmp,f);writeSummary(f,record,stamp);}
export function record(p,id){if(!/^[0-9TZ-]+-[a-f0-9]{8}$/.test(id))throw Error('Invalid run ID');return YAML.parse(fs.readFileSync(inside(p.repo,path.relative(p.repo,path.join(p.recordRoot,id,'regression.yaml'))),'utf8'));}
// The list index is derived and disposable. Size/mtime/inode bind it to the atomic YAML
// snapshot, so external CLI writes and legacy records cannot leave stale list results.
function signature(f){const s=fs.statSync(f);return [s.size,s.mtimeMs,s.ino];}
function writeSummary(f,r,stamp=signature(f)){const target=path.join(path.dirname(f),'summary.json');const tmp=target+'.'+process.pid+'.tmp';const value={signature:stamp,summary:{id:r.id,runId:r.runId||r.id,roundNumber:r.roundNumber||1,name:r.name,durationMs:r.durationMs,state:r.state,startedAt:r.startedAt,counts:r.counts}};try{fs.writeFileSync(tmp,JSON.stringify(value),{mode:0o600});fs.renameSync(tmp,target);}catch{/* Read-only historical stores remain readable without the optional index. */}return value.summary;}
function summary(p,id){if(!/^[0-9TZ-]+-[a-f0-9]{8}$/.test(id))throw Error('Invalid run ID');const f=inside(p.repo,path.relative(p.repo,path.join(p.recordRoot,id,'regression.yaml')));try{const index=JSON.parse(fs.readFileSync(path.join(path.dirname(f),'summary.json'),'utf8'));if(index.summary?.id===id&&typeof index.summary.name==='string'&&typeof index.summary.startedAt==='string'&&JSON.stringify(index.signature)===JSON.stringify(signature(f)))return index.summary;}catch{}const stamp=signature(f);return writeSummary(f,record(p,id),stamp);}
export function records(p){if(!fs.existsSync(p.recordRoot))return [];return fs.readdirSync(p.recordRoot).filter(id=>/^[0-9TZ-]+-[a-f0-9]{8}$/.test(id)).map(id=>{try{return summary(p,id);}catch{return null;}}).filter(Boolean).sort((a,b)=>b.startedAt.localeCompare(a.startedAt));}
export function recover(p){for(const r of records(p))if(r.state==='running'){const full=record(p,r.id);if(Number.isInteger(full.ownerPid)){try{process.kill(full.ownerPid,0);continue;}catch(error){if(error.code!=='ESRCH')continue;}}full.state='interrupted';full.finishedAt=new Date().toISOString();for(const c of full.cases)if(c.status==='running')c.status='error';save(p,full);}}

// Execution records remain immutable round snapshots. Legacy records are single-round runs.
export function rounds(p,runId){const root=summary(p,runId);const canonical=root.runId||root.id;return records(p).filter(x=>(x.runId||x.id)===canonical).map(x=>record(p,x.id)).sort((a,b)=>a.startedAt.localeCompare(b.startedAt)||a.id.localeCompare(b.id));}
export function runs(p){const items=records(p),byId=new Map(items.map(x=>[x.id,x])),groups=new Map();for(const item of items){const key=item.runId||item.id;const g=groups.get(key)||{...item,id:key,name:byId.get(key)?.name||item.name,durationMs:0,roundCount:0};g.durationMs+=item.durationMs||0;g.roundCount++;groups.set(key,g);}return [...groups.values()].sort((a,b)=>b.startedAt.localeCompare(a.startedAt));}
export function runRecord(p,id){const history=rounds(p,id);const latest=new Map();for(const round of history)for(const c of round.cases)if(['passed','failed','blocked','error','cancelled'].includes(c.status))latest.set(c.id,{...c,roundId:round.id,roundNumber:round.roundNumber||1});const counts={};for(const c of latest.values())counts[c.status]=(counts[c.status]||0)+1;return {id:history[0].runId||history[0].id,name:history[0].name,rounds:history,cases:[...latest.values()],counts};}

export function latestResult(p,id){const r=runRecord(p,id);return {id:r.id,name:r.name,view:'latest',cases:r.cases,counts:r.counts};}
