import fs from 'node:fs';import path from 'node:path';import YAML from 'yaml';import {inside} from '../lib/paths.mjs';
export function save(p,record){const dir=inside(p.repo,path.relative(p.repo,path.join(p.recordRoot,record.id)));fs.mkdirSync(dir,{recursive:true});const f=path.join(dir,'regression.yaml'),tmp=f+'.tmp';fs.writeFileSync(tmp,YAML.stringify(record),{mode:0o600});fs.renameSync(tmp,f);}
export function record(p,id){if(!/^[0-9TZ-]+-[a-f0-9]{8}$/.test(id))throw Error('Invalid run ID');return YAML.parse(fs.readFileSync(inside(p.repo,path.relative(p.repo,path.join(p.recordRoot,id,'regression.yaml'))),'utf8'));}
export function records(p){if(!fs.existsSync(p.recordRoot))return [];return fs.readdirSync(p.recordRoot).filter(id=>/^[0-9TZ-]+-[a-f0-9]{8}$/.test(id)).map(id=>{try{const r=record(p,id);return {id,name:r.name,durationMs:r.durationMs,state:r.state,startedAt:r.startedAt,counts:r.counts};}catch{return null;}}).filter(Boolean).sort((a,b)=>b.startedAt.localeCompare(a.startedAt));}
export function recover(p){for(const r of records(p))if(r.state==='running'){const full=record(p,r.id);if(Number.isInteger(full.ownerPid)){try{process.kill(full.ownerPid,0);continue;}catch(error){if(error.code!=='ESRCH')continue;}}full.state='interrupted';full.finishedAt=new Date().toISOString();for(const c of full.cases)if(c.status==='running')c.status='error';save(p,full);}}

// Execution records remain immutable round snapshots. Legacy records are single-round runs.
export function rounds(p,runId){const root=record(p,runId);const canonical=root.runId||root.id;return records(p).map(x=>record(p,x.id)).filter(x=>(x.runId||x.id)===canonical).sort((a,b)=>a.startedAt.localeCompare(b.startedAt)||a.id.localeCompare(b.id));}
export function runs(p){const groups=new Map();for(const item of records(p)){const r=record(p,item.id),key=r.runId||r.id;const g=groups.get(key)||{...item,id:key,name:record(p,key).name,durationMs:0,roundCount:0};g.durationMs+=r.durationMs||0;g.roundCount++;groups.set(key,g);}return [...groups.values()].sort((a,b)=>b.startedAt.localeCompare(a.startedAt));}
export function runRecord(p,id){const history=rounds(p,id);const latest=new Map();for(const round of history)for(const c of round.cases)if(['passed','failed','blocked','error','cancelled'].includes(c.status))latest.set(c.id,{...c,roundId:round.id,roundNumber:round.roundNumber||1});const counts={};for(const c of latest.values())counts[c.status]=(counts[c.status]||0)+1;return {id:history[0].runId||history[0].id,name:history[0].name,rounds:history,cases:[...latest.values()],counts};}

export function latestResult(p,id){const r=runRecord(p,id);return {id:r.id,name:r.name,view:'latest',cases:r.cases,counts:r.counts};}
