import {schedule,caseLocks} from './scheduler.mjs';
import {resolveEnvironment,checkEnvironment,requiredResources} from '../environment/resolver.mjs';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {plan} from '../cases/catalog.mjs';import {save,record,rounds} from '../record_store/store.mjs';import {inside} from '../lib/paths.mjs';
const jobs=new Map();const worker=fileURLToPath(new URL('./worker.mjs',import.meta.url));
const id=()=>new Date().toISOString().replace(/[-:.]/g,'').replace(/\d{3}Z$/,'Z')+'-'+crypto.randomBytes(4).toString('hex');
function stop(child){if(!child||child.exitCode!==null)return;try{process.kill(-child.pid,'SIGTERM');}catch{}setTimeout(()=>{if(child.exitCode===null)try{process.kill(-child.pid,'SIGKILL');}catch{}},2000).unref();}
export function cancelRepository(repo){for(const [id,job] of jobs)if(job.repo===repo)cancel(id);}
export function cancel(id){const j=jobs.get(id);if(!j)throw Error('Run not active in this server');j.cancelled=true;for(const child of j.children)stop(child);return {id,cancelRequested:true};}
export function start(p,args={}){const parent=args.runId?record(p,args.runId):null;const rootId=parent?(parent.runId||parent.id):null;const history=rootId?rounds(p,rootId):[];if(history.some(r=>r.state==='running'))throw Error('A round is already running');const selection=plan(p,args);args=selection.filters;if(selection.diagnostics.length)throw Error('Fix catalog diagnostics before execution');if(!selection.selected)throw Error('No selected cases');if([...jobs.values()].some(j=>j.repo===p.repo))throw Error('A run is already active for this repository');
 const run={schemaVersion:2,ownerPid:process.pid,id:id(),runId:rootId,roundNumber:history.length+1,name:args.name||new Date().toISOString().slice(0,19)+' · '+selection.profile,startedAt:new Date().toISOString(),state:'running',durationMs:0,profile:selection.profile,filters:selection.filters,environment:{baseUrl:p.config.baseUrl||null,browserMode:p.config.browser?.mode||'device'},cases:selection.items.map(c=>({...c,status:c.selected?'pending':'excluded'}))};run.runId=run.runId||run.id;const job={repo:p.repo,cancelled:false,children:new Set()};jobs.set(run.id,job);save(p,run);const begin=performance.now();
 const completion=(async()=>{try{const resolved=await resolveEnvironment(p,args,requiredResources(selection.items));run.environment={...run.environment,...resolved.snapshot};save(p,run);await schedule(run.cases.filter(c=>c.selected),args.concurrency||1,caseLocks,async c=>{if(job.cancelled){c.status='cancelled';return;}const missing=(c.meta.requires||[]).filter(r=>!p.config.prerequisites?.[r]);if(missing.length){c.status='blocked';c.error='Missing prerequisites: '+missing.join(', ');save(p,run);return;}if(c.meta.effects==='external-write'&&!args.allowExternalWrites){c.status='blocked';c.error='External writes require explicit selection authorization';save(p,run);return;}
 c.preflight=await checkEnvironment(resolved,c.requirements);if(!c.preflight.ready){c.status='blocked';c.error=c.preflight.checks.filter(x=>!x.ready).map(x=>x.reason).join('; ');save(p,run);return;}
 if(job.cancelled){c.status='cancelled';save(p,run);return;}
 c.status='running';c.startedAt=new Date().toISOString();save(p,run);const dir=inside(p.repo,path.relative(p.repo,path.join(p.recordRoot,run.id))),input=path.join(dir,c.id+'-worker-input.json'),output=path.join(dir,c.id+'-worker-output.json');fs.writeFileSync(input,JSON.stringify({repo:p.repo,case:c,config:p.config,resources:resolved.snapshot.resources,parameters:resolved.snapshot.parameters,runId:run.id,evidenceDir:path.join(dir,'evidence')}),{mode:0o600});
 let timedOut=false;await new Promise(resolve=>{const child=spawn(process.execPath,[worker,input,output],{detached:true,stdio:'ignore'});job.children.add(child);const timer=setTimeout(()=>{timedOut=true;c.error='Case timeout';stop(child);},args.timeoutMs||60000);child.on('error',e=>{c.error=e.message;clearTimeout(timer);job.children.delete(child);resolve();});child.on('exit',()=>{clearTimeout(timer);job.children.delete(child);resolve();});});
 if(fs.existsSync(output)){const r=JSON.parse(fs.readFileSync(output));Object.assign(c,r);fs.unlinkSync(output);}if(timedOut){c.status='error';c.error='Case timeout';}if(c.status==='running'||c.status==='pending')c.status=job.cancelled?'cancelled':'error';fs.unlinkSync(input);c.finishedAt=new Date().toISOString();save(p,run);
 },()=>job.cancelled);}catch(e){run.error=e.message;for(const c of run.cases)if(c.status==='pending'){c.status='error';c.error='Runner setup failed';}}finally{run.state=job.cancelled?'cancelled':'completed';run.finishedAt=new Date().toISOString();run.durationMs=performance.now()-begin;run.counts={};for(const c of run.cases)run.counts[c.status]=(run.counts[c.status]||0)+1;save(p,run);jobs.delete(run.id);}return run;})();return {id:run.id,completion};}
