import {evaluatePerformance} from '../telemetry/assertions.mjs';
import {collectPerformance} from '../telemetry/collector.mjs';
import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {spawn} from 'node:child_process';import crypto from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {openBrowser,connectLease} from '../browser/runtime.mjs';import {inside,shortError} from '../lib/paths.mjs';
let driver;let cancelled=false;process.on('SIGTERM',async()=>{cancelled=true;await driver?.close();process.exit(143);});
const input=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));const output=process.argv[3];const {repo,case:c,config,evidenceDir}=input;let result={status:'running',steps:[],assertions:[],measurements:[],traces:[],traceRefs:[]};const started=performance.now();
function write(){fs.writeFileSync(output,JSON.stringify({...result,durationMs:performance.now()-started}),{mode:0o600});}write();
function fail(name,actual,expected){const ok=isDeepStrictEqual(actual,expected);result.assertions.push({name,kind:'functional',passed:ok,actual,expected});write();if(!ok){const e=Error(name);e.kind='failed';throw e;}}
async function step(name,target,fn){const t=performance.now();const row={name,target,status:'running'};result.steps.push(row);write();try{const v=await fn();row.status='passed';return v;}catch(e){row.status='failed';row.error=shortError(e);throw e;}finally{row.durationMs=performance.now()-t;write();}}
function capturePage(page){if(!config.telemetry)return;page.on('request',r=>{const h=r.headers(),match=h.traceparent?.match(/^00-([a-f0-9]{32})-/i);if(match&&!result.traceRefs.some(x=>x.traceId===match[1])){result.traceRefs.push({traceId:match[1],source:'gui'});write();}});}
const ctx={repo,resources:input.resources||{},parameters:input.parameters||{},baseUrl:config.baseUrl,input:config.input||{},runId:input.runId,caseId:c.id,
 assert:fail,
 async newPage(){if(!process.send||!driver)throw Error('Run-owned browser required');const requestId=crypto.randomUUID();const response=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{process.off('message',receive);reject(Error('Auxiliary tab allocation timeout'));},10000);function receive(m){if(m?.requestId!==requestId)return;clearTimeout(timer);process.off('message',receive);m.error?reject(Error(m.error)):resolve(m);}process.on('message',receive);process.send({type:'newPage',requestId});});const page=await driver.findPage(response.pageUrl);capturePage(page);return page;},
 block(reason){const e=Error(reason);e.kind='blocked';throw e;},
 async action(name,{target,action,value}){return step(name,target,async()=>{if(!ctx.page)throw Error('GUI context unavailable');const selector=config.targets?.[target];if(!selector)throw Error('Unregistered test target '+target);const l=ctx.page.locator(selector);if(action==='click')await l.click();else if(action==='fill')await l.fill(value);else throw Error('Unknown action');});},
 async observe(name,{target,read='text'}){return step(name,target,async()=>{const selector=config.targets?.[target];if(!selector)throw Error('Unregistered target');const l=ctx.page.locator(selector);return read==='count'?l.count():l.textContent();});},
 async measure(name,fn,{maximumMs}={}){const t=performance.now();const value=await step(name,null,fn),durationMs=performance.now()-t;result.measurements.push({name,kind:'runner-boundary',durationMs,maximumMs:maximumMs??null});if(maximumMs!=null){const passed=durationMs<=maximumMs;result.assertions.push({name,kind:'performance',passed,actual:durationMs,maximumMs,unit:'ms',boundary:'explicit runner scope; not a provider span'});write();if(!passed){const e=Error(name+' exceeded limit');e.kind='failed';throw e;}}return value;},
 async command(name,executable,args,{input:stdin,capture=true}={}){return step(name,null,()=>new Promise((resolve,reject)=>{const traceEnv={};for(const [key,param] of Object.entries(config.telemetry?.commandEnvironmentParameters||{})){const value=input.parameters?.[param];if(value!==undefined)traceEnv[key]=String(value);}if(config.telemetry?.commandTraceparentEnvironment&&(!config.telemetry.commandPathPrefix||args.some(a=>typeof a==='string'&&a.startsWith(config.telemetry.commandPathPrefix)))){const traceId=crypto.randomBytes(16).toString('hex');traceEnv[config.telemetry.commandTraceparentEnvironment]='00-'+traceId+'-'+crypto.randomBytes(8).toString('hex')+'-01';result.traceRefs.push({traceId,source:'command',name});}const child=spawn(executable,args,{cwd:repo,stdio:[stdin===undefined?'ignore':'pipe','pipe','pipe'],env:{...process.env,...traceEnv,TRACE_REGRESSION_RUN_ID:input.runId,TRACE_REGRESSION_CASE_ID:c.id}});if(stdin!==undefined)child.stdin.end(stdin);let stdout='',stderr='';child.stdout.on('data',b=>{stdout+=b;if(stdout.length>262144){child.kill();reject(Error('Command output limit'));}});child.stderr.on('data',b=>{stderr=(stderr+b).slice(-5000);});child.on('error',reject);child.on('exit',code=>{if(capture){result.outputs??=[];result.outputs.push({name,code,stdout:shortError(stdout.slice(0,3000)),stderr:shortError(stderr),truncated:stdout.length>3000});}write();resolve({code,stdout,stderr});});}));},
 async performance(name,{entryId,traceId,maximumMs}){if(config.telemetry){if(!entryId||!Number.isFinite(maximumMs)||maximumMs<0)throw Error('Performance assertion requires registered entryId and explicit nonnegative maximumMs');result.performanceChecks??=[];result.performanceChecks.push({name,entryId,traceId,maximumMs});write();return;}if(!config.telemetryAdapter){result.assertions.push({name,kind:'performance',passed:false,state:'inconclusive',reason:'No telemetry adapter configured'});ctx.block('Provider performance requires a project telemetry adapter');}const adapter=await import(pathToFileURL(inside(repo,config.telemetryAdapter)).href);const measurement=await adapter.performance({traceId,runId:input.runId,caseId:c.id});if(!Number.isFinite(measurement.durationMs))ctx.block('Telemetry unavailable');if(measurement.boundary!=='operation-end-to-end'||!measurement.entryId)ctx.block('Telemetry must identify the operation end-to-end boundary; individual span timing is not accepted');result.traces.push({traceId,...measurement});const passed=measurement.durationMs<=maximumMs;result.assertions.push({name,kind:'performance',passed,actual:measurement.durationMs,maximumMs,unit:'ms',boundary:'provider trace'});write();if(!passed){const e=Error(name);e.kind='failed';throw e;}},
 async screenshot(name){if(!ctx.page)throw Error('No GUI page');fs.mkdirSync(evidenceDir,{recursive:true,mode:0o700});const file=path.join(evidenceDir,crypto.randomUUID()+'.png');await ctx.page.screenshot({path:file});result.evidence??=[];result.evidence.push({name,path:path.relative(repo,file)});write();},
};
try{
 const file=inside(repo,c.file);if(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')!==c.digest)throw Error('Case changed after planning');
 if(c.meta.surface==='gui'){driver=input.browserLease?await connectLease(input.browserLease):await openBrowser(config.browser);ctx.page=driver.page;capturePage(ctx.page);result.diagnostics=[];ctx.page.on('pageerror',e=>{result.diagnostics.push({kind:'pageerror',message:shortError(e)});write();});ctx.page.on('response',r=>{if(r.status()>=400){result.diagnostics.push({kind:'http',path:new URL(r.url()).pathname,status:r.status()});write();}});ctx.page.on('requestfailed',r=>{result.diagnostics.push({kind:'requestfailed',path:new URL(r.url()).pathname,error:r.failure()?.errorText});write();});await ctx.page.goto(config.baseUrl,{waitUntil:'domcontentloaded'});if(config.readySelector)await ctx.page.locator(config.readySelector).waitFor({timeout:30000});}
 const module=await import(pathToFileURL(file).href);let primary;try{await module.run(ctx);}catch(e){primary=e;}finally{if(module.cleanup)try{await module.cleanup(ctx);}catch(e){result.cleanupError=shortError(e);if(!primary)primary=e;}}if(primary)throw primary;
 if(!result.assertions.length&&!result.performanceChecks?.length)throw Error('No explicit assertions executed');result.status='passed';
}catch(e){result.status=e.kind||'error';result.error=shortError(e);if(ctx.page)try{await ctx.screenshot('Failure state');}catch{} }
finally{if(config.telemetry&&result.traceRefs.length&&!cancelled)try{const collected=await collectPerformance({repo,config:config.telemetry,parameters:input.parameters,refs:result.traceRefs});result.traces.push(...collected.samples);result.telemetryDiagnostics=collected.diagnostics;}catch(e){result.telemetryDiagnostics=[{state:'unavailable',reason:shortError(e)}];}if(result.performanceChecks?.length){const assertions=evaluatePerformance(result.performanceChecks,result.traces);result.assertions.push(...assertions);if(result.status==='passed'&&assertions.some(a=>!a.passed)){result.status=assertions.some(a=>a.state==='inconclusive')?'blocked':'failed';result.error=assertions.filter(a=>!a.passed).map(a=>a.reason||a.name+' exceeded limit').join('; ');}}try{await driver?.close();}catch(e){result.cleanupError=shortError(e);if(result.status==='passed')result.status='error';}if(!cancelled)write();}
