import {RunRegression} from './run-regression';
import {useEffect,useState} from 'react';import {Play} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Skeleton} from '@/components/ui/skeleton';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectGroup,SelectItem} from '@/components/ui/select';
import {Field,FieldLabel,FieldGroup} from '@/components/ui/field';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {api,TestCase,label} from '@/lib/api';import {CaseSheet,ScriptLink,ErrorNotice,MetaValue} from './shared';
export function Filter({id,title,value,onChange,options}:{id:string;title:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <Field orientation="horizontal" className="w-auto"><FieldLabel htmlFor={id} className="whitespace-nowrap">{title}</FieldLabel><Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectGroup>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectGroup></SelectContent></Select></Field>;}
export function Cases({onRun}:{onRun:(id:string)=>void}){
 const [data,setData]=useState<{cases:TestCase[];diagnostics:any[]}|null>(null),[status,setStatus]=useState('all'),[module,setModule]=useState('all'),[entry,setEntry]=useState('all'),[item,setItem]=useState<TestCase|null>(null),[error,setError]=useState<string|null>(null),[dialog,setDialog]=useState(false);
 useEffect(()=>{api('cases').then(setData).catch(e=>setError(e.message));},[]);
 const rows=(data?.cases||[]).filter(c=>(status==='all'||c.meta.status===status)&&(module==='all'||(c.meta.module===module||c.meta.module.startsWith(module+'/')))&&(entry==='all'||c.meta.surface===entry)).sort((a,b)=>a.meta.module.localeCompare(b.meta.module)||a.name.localeCompare(b.name));
 const modules=[...new Set((data?.cases||[]).flatMap(c=>c.meta.module.split('/').map((_:string,i:number)=>c.meta.module.split('/').slice(0,i+1).join('/'))))].sort();
 return <div className="flex flex-col gap-6 p-8"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">Test cases</h1><p className="mt-2 text-sm text-muted-foreground">{data?`${rows.length} ${rows.length===1?'case':'cases'} · ${rows.filter(c=>c.runnable).length} implemented · ${rows.filter(c=>!c.runnable).length} case only`:'Loading cases'}</p></div><Button onClick={()=>setDialog(true)} disabled={!data}><Play data-icon="inline-start"/>Run regression</Button></div>
 <ErrorNotice error={error||data?.diagnostics.map(d=>d.file+': '+d.error).join('; ')||null}/>
 <FieldGroup className="flex flex-row flex-wrap items-center gap-6"><Filter id="case-status" title="Status" value={status} onChange={setStatus} options={['trial','active','rotten','obsolete','all'].map(v=>[v,v==='all'?'All statuses':label('status',v)])}/><Filter id="case-module" title="Module" value={module} onChange={setModule} options={[['all','All modules'],...modules.map(v=>[v,'　'.repeat(v.split('/').length-1)+v.split('/').at(-1)] as [string,string])]}/><Filter id="case-entry" title="Entry" value={entry} onChange={setEntry} options={[['all','All entries'],['gui','GUI'],['skill','Agent command'],['integration','Integration']]}/></FieldGroup>
 {!data?<Skeleton className="h-48 w-full"/>:!rows.length?<Empty><EmptyHeader><EmptyTitle>No matching cases</EmptyTitle><EmptyDescription>Choose a different status, module or entry.</EmptyDescription></EmptyHeader></Empty>:<div className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead className="pl-5">Name</TableHead><TableHead>Module</TableHead><TableHead>Entry</TableHead><TableHead>Priority</TableHead><TableHead>Added for</TableHead><TableHead>Duration class</TableHead><TableHead>Status</TableHead><TableHead>Implementation</TableHead><TableHead className="text-right pr-5">Source</TableHead></TableRow></TableHeader><TableBody>{rows.map(c=><TableRow key={c.id} tabIndex={0} aria-label={c.name} className="cursor-pointer" onClick={()=>setItem(c)} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setItem(c);}}}><TableCell className="max-w-sm whitespace-normal pl-5 font-medium">{c.name}</TableCell><TableCell><MetaValue field="module" value={c.meta.module}/></TableCell><TableCell><MetaValue field="surface" value={c.meta.surface}/></TableCell><TableCell><MetaValue field="priority" value={c.meta.priority}/></TableCell><TableCell><MetaValue field="origin" value={c.meta.origin}/></TableCell><TableCell><MetaValue field="cost" value={c.meta.cost}/></TableCell><TableCell><MetaValue field="status" value={c.meta.status}/></TableCell><TableCell><MetaValue field="implementation" value={c.runnable?'Implemented':'Case only'}/></TableCell><TableCell className="text-right pr-5"><ScriptLink id={c.id} caseOnly={!c.runnable}/></TableCell></TableRow>)}</TableBody></Table></div>}
 <CaseSheet item={item} onClose={()=>setItem(null)}/>
 {dialog&&<RunRegression initialMeta={{...(status==='all'?{}:{status:[status]}),...(module==='all'?{}:{module:[module]}),...(entry==='all'?{}:{surface:[entry]})}} onClose={()=>setDialog(false)} onRun={onRun}/>}
 </div>;
}
