import {useEffect,useRef,useState} from 'react';import {ExternalLink} from 'lucide-react';
import {SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';import {Badge} from '@/components/ui/badge';import {Button} from '@/components/ui/button';import {Skeleton} from '@/components/ui/skeleton';import {Alert,AlertDescription} from '@/components/ui/alert';import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {api} from '@/lib/api';import {ErrorNotice} from './shared';
type Operation={id:string;description:string;owner:string;source:{path:string;object?:string;function?:string};entry:{kind:string;executable?:string;args?:string[]}};
const sourceLabel=(o:Operation)=>[o.source.path,o.source.object,o.source.function].filter(Boolean).join(' → ');
// Provider queries are lazy and bounded; no percentile is inferred from a trace sample list.
let active=0;const queue:(()=>void)[]=[];
function limited<T>(f:()=>Promise<T>){return new Promise<T>((resolve,reject)=>{queue.push(()=>{active++;f().then(resolve,reject).finally(()=>{active--;pump();});});pump();});}
function pump(){while(active<3&&queue.length)queue.shift()!();}
function OperationItem({o,selected,onSelect}:{o:Operation;selected:boolean;onSelect:()=>void}){
 const ref=useRef<HTMLLIElement>(null),[metrics,setMetrics]=useState<any>(null),[error,setError]=useState(false);
 useEffect(()=>{let valid=true;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();limited(()=>api('operation_metrics',{operation:o.id})).then(v=>{if(valid)setMetrics(v);}).catch(()=>{if(valid)setError(true);});}});if(ref.current)observer.observe(ref.current);return()=>{valid=false;observer.disconnect();};},[o.id]);
 const points=metrics?[['P50',metrics.p50Ms],['P90',metrics.p90Ms],['P95',metrics.p95Ms]].filter(([,v])=>Number.isFinite(v)):[];
 return <SidebarMenuItem ref={ref}><SidebarMenuButton isActive={selected} onClick={onSelect} className="h-auto items-start whitespace-normal p-4"><div className="flex min-w-0 flex-col gap-3"><span className="font-medium">{o.id}</span><span className="text-sm leading-6 text-muted-foreground">{o.description}</span><Badge variant="secondary">{o.owner}</Badge><span className="break-all font-mono text-xs text-muted-foreground">{sourceLabel(o)}</span><span className="text-xs tabular-nums text-muted-foreground">{error?'Performance samples unavailable':!metrics?'Loading performance samples…':points.length?'Last hour · '+points.map(([p,v])=>p+' '+Number(Number(v).toFixed(2))+' ms').join(' · '):'No performance samples in the last hour'}</span></div></SidebarMenuButton></SidebarMenuItem>;
}
export function Performance(){
 const [ops,setOps]=useState<Operation[]|null>(null),[selected,setSelected]=useState<Operation|null>(null),[location,setLocation]=useState<any>(null),[embed,setEmbed]=useState<string|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState<string|null>(null);
 const frame=useRef<HTMLIFrameElement>(null),loaded=useRef(false),request=useRef<{id:string;origin:string}|null>(null),sequence=useRef(0);
 function locate(){const r=request.current;if(r&&loaded.current)frame.current?.contentWindow?.postMessage({type:'trace.locate',id:r.id},r.origin);}
 useEffect(()=>{function receive(e:MessageEvent){const r=request.current;if(r&&e.source===frame.current?.contentWindow&&e.origin===r.origin&&e.data?.type==='trace.result'&&e.data.id===r.id)setNotice(e.data.ok?'':e.data.message||'Target unavailable');}window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[]);
 async function choose(o:Operation){setSelected(o);setLocation(null);setError(null);setNotice('');request.current=null;const mine=++sequence.current;try{const v=await api('locate',{operation:o.id});if(mine!==sequence.current)return;setLocation(v);if(o.entry.kind==='gui'&&v.embedUrl){const url=new URL(v.embedUrl);if(!['http:','https:'].includes(url.protocol))throw Error('Unsupported preview URL');request.current={id:o.id,origin:url.origin};setEmbed(old=>{if(old!==url.href)loaded.current=false;return url.href;});locate();}}catch(e:any){if(mine===sequence.current)setError(e.message);}}
 useEffect(()=>{let valid=true;api<{operations:Operation[]}>('operations').then(v=>{if(!valid)return;setOps(v.operations);const id=new URL(window.location.href).searchParams.get('operation');const initial=v.operations.find(o=>o.id===id)||v.operations[0];if(initial)void choose(initial);}).catch(e=>{if(valid)setError(e.message);});return()=>{valid=false;};},[]);
 return <div className="flex h-full min-h-0 flex-col md:flex-row"><aside className="max-h-80 w-full shrink-0 overflow-y-auto border-b p-3 md:max-h-none md:w-96 md:border-r md:border-b-0"><SidebarMenu>{!ops?<Skeleton className="h-64 w-full"/>:ops.map(o=><OperationItem key={o.id} o={o} selected={selected?.id===o.id} onSelect={()=>void choose(o)}/>)}</SidebarMenu></aside><section className="flex min-h-0 min-w-0 flex-1 flex-col">{selected?<><header className="flex shrink-0 items-center justify-between gap-4 border-b px-6 py-4"><code className="break-all text-xs text-muted-foreground">{sourceLabel(selected)}</code>{location?.grafanaUrl&&<Button variant="link" size="sm" asChild><a href={location.grafanaUrl} target="_blank" rel="noreferrer">Grafana<ExternalLink data-icon="inline-end"/></a></Button>}</header>{error&&<div className="p-4"><ErrorNotice error={error}/></div>}{notice&&<Alert className="rounded-none border-x-0"><AlertDescription>{notice}</AlertDescription></Alert>}<div className="relative min-h-0 flex-1">{embed&&<iframe ref={frame} title="Operation preview" src={embed} onLoad={()=>{loaded.current=true;locate();}} hidden={selected.entry.kind!=='gui'} className="h-full w-full border-0"/>}{selected.entry.kind==='command'?<pre className="m-6 overflow-auto rounded-md border bg-muted/30 p-4 text-sm"><code>{[selected.entry.executable,...selected.entry.args||[]].join(' ')}</code></pre>:selected.entry.kind==='internal'?<Empty><EmptyHeader><EmptyTitle>Internal operation</EmptyTitle><EmptyDescription>No interactive entry is registered.</EmptyDescription></EmptyHeader></Empty>:location&&!location.embedUrl&&<Empty><EmptyHeader><EmptyTitle>No embedded preview configured</EmptyTitle><EmptyDescription>{location.url?<a href={location.url} target="_blank" rel="noreferrer">Open operation preview</a>:'Configure a project GUI locator adapter.'}</EmptyDescription></EmptyHeader></Empty>}</div></>:<div className="p-8"><ErrorNotice error={error}/></div>}</section></div>;
}
