import {groupResults} from '../../../../regression_test/record_store/grouping.mjs';
import {Filter} from './cases';
import {RunRegression} from './run-regression';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {Textarea} from '@/components/ui/textarea';
import {useEffect,useState} from 'react';import {Copy,Check,StopCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Switch} from '@/components/ui/switch';import {Field,FieldLabel} from '@/components/ui/field';import {Skeleton} from '@/components/ui/skeleton';
import {SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Badge} from '@/components/ui/badge';import {ScrollArea} from '@/components/ui/scroll-area';
import {api,Regression,TestCase,duration,selectionReason,label} from '@/lib/api';import {Outcome,CaseSheet,ScriptLink,ErrorNotice} from './shared';
const date=(s:string)=>new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'medium'}).format(new Date(s));
export function Records({initialId,initialRound,onSelect}:{initialId:string|null;initialRound:string|null;onSelect:(id:string,round?:string)=>void}){
 const prefs=new URL(window.location.hash.slice(1)||'/records','http://trace.local').searchParams;
 const [scope,setScope]=useState(prefs.get('results')==='round'?'round':'latest'),[groupBy,setGroupBy]=useState(prefs.get('groupBy')||'module'),[depth,setDepth]=useState(prefs.get('moduleDepth')||'1'),[selectedGroup,setSelectedGroup]=useState<string|null>(null),[compare,setCompare]=useState(false);
 const [rerun,setRerun]=useState(false),[revision,setRevision]=useState(0);
 const [latest,setLatest]=useState<any>(null);
 const [history,setHistory]=useState<Regression[]>([]),[prompt,setPrompt]=useState(''),[copied,setCopied]=useState(false);
 const [list,setList]=useState<any[]|null>(null),[id,setId]=useState<string|null>(initialId),[run,setRun]=useState<Regression|null>(null),[item,setItem]=useState<TestCase|null>(null),[problems,setProblems]=useState(false),[error,setError]=useState<string|null>(null),[cancelling,setCancelling]=useState(false);
 useEffect(()=>{let valid=true;api('records').then(v=>{if(valid){setList(v);setId(old=>old||v[0]?.id||null);if(!initialId&&v[0])onSelect(v[0].id);}}).catch(e=>setError(e.message));return()=>{valid=false;};},[]);
 useEffect(()=>{if(initialId)setId(initialId);},[initialId]);
 useEffect(()=>{if(!id)return;let valid=true,timer:ReturnType<typeof setTimeout>;setRun(null);setError(null);setPrompt('');async function load(){try{const group=await api<any>('run_record',{id});if(!valid)return;const r=group.rounds.at(-1);setHistory(group.rounds);setLatest(group);setRun({...r,name:group.name});setList(old=>old?.map(x=>x.id===id?{...x,durationMs:group.rounds.reduce((sum:number,x:Regression)=>sum+(x.durationMs||0),0)}:x)||null);void api<any>('ask_agent',{id}).then(v=>{if(valid)setPrompt(v.prompt);}).catch(e=>{if(valid)setError(e.message);});if(r.state==='running')timer=setTimeout(load,1000);}catch(e:any){if(valid)setError(e.message);}}load();return()=>{valid=false;clearTimeout(timer);};},[id,revision]);
 useEffect(()=>{if(!history.length||latest?.id!==id)return;const selected=history.find(r=>r.id===initialRound)||history.at(-1)!;setRun({...selected,name:latest.name});setItem(null);},[history,initialRound,id,latest]);

 const results:TestCase[]=scope==='latest'?(latest?.cases||[]):(run?.cases||[]).filter(c=>c.status!=='excluded');
 const fields=[...new Set(results.flatMap(c=>Object.keys(c.meta||{})))].filter(k=>!['id','statusReason'].includes(k)).sort();
 const titles:Record<string,string>={module:'Module',priority:'Priority',surface:'Entry',origin:'Added for',status:'Maturity',effects:'Effects',cost:'Duration class',covers:'Coverage',requires:'Prerequisites',affectedPaths:'Affected paths',suite:'Suite',testLevel:'Test level'};
 const effectiveField=fields.includes(groupBy)?groupBy:fields[0];
 const groups=effectiveField?groupResults(results,effectiveField,{moduleDepth:effectiveField==='module'&&depth!=='all'?Number(depth):undefined}):[];
 const chosen=groups.find(g=>g.key===selectedGroup);
 useEffect(()=>{const update=()=>{const u=new URL(window.location.hash.slice(1)||'/records','http://trace.local');if(!u.pathname.startsWith('/records'))return;setScope(u.searchParams.get('results')==='round'?'round':'latest');setGroupBy(u.searchParams.get('groupBy')||'module');setDepth(u.searchParams.get('moduleDepth')||'1');};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 const rows=(chosen?.cases||results).filter(c=>!problems||c.status!=='passed');
 useEffect(()=>setSelectedGroup(null),[id,scope,groupBy,depth,initialRound]);
 useEffect(()=>{const u=new URL(window.location.hash.slice(1)||'/records','http://trace.local');u.searchParams.set('groupBy',groupBy);u.searchParams.set('moduleDepth',depth);u.searchParams.set('results',scope);window.history.replaceState(null,'','#'+u.pathname+u.search);},[scope,groupBy,depth,id,initialRound]);

 return <div className="flex h-full min-h-0 overflow-hidden"><aside aria-label="Regression history" className="flex h-full min-h-0 w-64 shrink-0 flex-col border-r bg-sidebar"><h2 className="shrink-0 px-5 pt-6 pb-4 text-xs font-medium text-muted-foreground">Regression history</h2><ScrollArea type="always" className="min-h-0 flex-1 px-3 pb-6">{!list?<Skeleton className="h-32 w-full"/>:<SidebarMenu>{list.map(r=><SidebarMenuItem key={r.id}><SidebarMenuButton size="lg" isActive={r.id===id} onClick={()=>{setItem(null);setId(r.id);onSelect(r.id);}} className="h-auto py-3"><div className="flex min-w-0 flex-col gap-1"><span className="truncate">{r.name.includes('T')?date(r.startedAt)+' · '+r.name.split(' · ').at(-1):r.name}</span><span className="text-xs text-muted-foreground">{duration(r.durationMs)} · {r.roundCount||1} {(r.roundCount||1)===1?'round':'rounds'}</span></div></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>}</ScrollArea></aside>
 <section className="flex min-h-0 min-w-0 flex-1 flex-col gap-6 overflow-y-auto p-8 [&>*]:shrink-0"><ErrorNotice error={error}/>{!list?<Skeleton className="h-48 w-full"/>:!id?<Empty><EmptyHeader><EmptyTitle>No regression records</EmptyTitle><EmptyDescription>Run selected test cases to create a record.</EmptyDescription></EmptyHeader></Empty>:!run?<Skeleton className="h-48 w-full"/>:<><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{run.name.includes('T')?'Regression':run.name}</h1><p className="mt-2 text-sm text-muted-foreground">{date(run.startedAt)}</p></div><Button variant="secondary" onClick={()=>setRerun(true)} disabled={history.some(r=>r.state==='running')}>New round</Button><Popover><PopoverTrigger asChild><Button variant="outline">Ask Agent</Button></PopoverTrigger><PopoverContent align="end" className="w-[min(36rem,calc(100vw-2rem))] space-y-3"><p className="text-sm">Copy to your agent and add your question.</p><Textarea readOnly aria-label="Ask Agent instructions" value={prompt} className="min-h-40 font-mono text-xs"/><Button size="sm" onClick={async()=>{try{await navigator.clipboard.writeText(prompt);setCopied(true);}catch(e:any){setError(e.message);}}}>{copied?<Check/>:<Copy/>}{copied?'Copied':'Copy'}</Button></PopoverContent></Popover>{run.state==='running'&&<Button variant="outline" disabled={cancelling} onClick={async()=>{setCancelling(true);try{await api('cancel',{id:run.id},true);}catch(e:any){setError(e.message);}finally{setCancelling(false);}}}><StopCircle data-icon="inline-start"/>Cancel run</Button>}</div>
 <div className="flex flex-wrap gap-2">{history.map((r,i)=><Button key={r.id} variant={run.id===r.id?'secondary':'outline'} onClick={()=>{if(id)onSelect(id,r.id);setItem(null);}}>Round {r.roundNumber||i+1}</Button>)}</div>
 {compare&&history.length>1&&<div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead className="sticky left-0 z-10 min-w-80 max-w-80 bg-background">Case · round comparison</TableHead><TableHead className="sticky left-80 z-10 min-w-44 bg-background">Latest round result</TableHead>{history.map((r,i)=><TableHead key={r.id}>Round {r.roundNumber||i+1}</TableHead>)}</TableRow></TableHeader><TableBody>{[...new Map(history.flatMap(r=>r.cases.filter(c=>c.status!=='excluded').map(c=>[c.id,c] as const))).values()].map(c=><TableRow key={c.id}><TableCell className="sticky left-0 z-10 min-w-80 max-w-80 whitespace-normal bg-background">{c.name}</TableCell><TableCell className="sticky left-80 z-10 min-w-44 bg-background">{(()=>{const result=latest?.cases.find((x:any)=>x.id===c.id);return result?<button className="flex cursor-pointer flex-col items-start gap-1" onClick={()=>setItem(result)}><Outcome status={result.status}/><span className="text-xs text-muted-foreground">Round {result.roundNumber}</span></button>:'—';})()}</TableCell>{history.map(r=>{const result=r.cases.find(x=>x.id===c.id&&x.status!=='excluded');return <TableCell key={r.id}>{result?<button className="cursor-pointer" onClick={()=>setItem(result)}><Outcome status={result.status||'pending'}/></button>:'—'}</TableCell>;})}</TableRow>)}</TableBody></Table></div>}
 <dl className="grid grid-cols-2 gap-6 border-b pb-6 lg:grid-cols-4">{[['Round status',run.state[0].toUpperCase()+run.state.slice(1)],['Round duration',duration(run.durationMs)],['Round scope',run.filters?.validateInactive?'Case validation':run.filters?.ids||run.filters?.meta?.id?'Selected cases':run.filters?.surface||run.filters?.meta?.surface?'Selected entry type':run.filters?.meta&&Object.keys(run.filters.meta).some(k=>k!=='status')?'Metadata selection':run.profile==='full'?'Full regression':'Release checks'],['Browser',!run.cases.some(c=>c.meta.surface==='gui'&&c.status!=='excluded')?'Not used':run.environment.browserMode==='device'?'Chrome · CDP':'Headless Chromium']].map(([title,text])=><div key={title}><dt className="text-xs text-muted-foreground">{title}</dt><dd className="mt-2 text-sm font-medium">{title==='Round status'?<Outcome status={run.state==='completed'?run.cases.some(c=>['failed','error'].includes(c.status||''))?'failed':run.cases.some(c=>c.status==='blocked')?'blocked':run.cases.some(c=>c.status==='cancelled')?'cancelled':run.cases.some(c=>c.status==='passed')?'passed':'excluded':run.state}/>:<Badge variant="secondary">{text}</Badge>}</dd></div>)}</dl>
 <div className="flex flex-wrap items-center gap-6"><Filter id="result-scope" title="Results" value={scope} onChange={setScope} options={[["latest","Latest results"],["round","Selected round"]]}/><Filter id="result-group" title="Group by" value={effectiveField||groupBy} onChange={setGroupBy} options={fields.map(k=>[k,titles[k]||k])}/>{effectiveField==='module'&&<Filter id="result-depth" title="Module depth" value={depth} onChange={setDepth} options={[["1","Level 1"],["2","Level 2"],["3","Level 3"],["all","Full path"]]}/>}<Field orientation="horizontal" className="w-auto"><Switch id="problems" checked={problems} onCheckedChange={setProblems}/><FieldLabel htmlFor="problems">Problems only</FieldLabel></Field>{history.length>1&&<Button variant="outline" onClick={()=>setCompare(v=>!v)}>{compare?'Hide round comparison':'Compare rounds'}</Button>}</div>
 <p className="text-sm text-muted-foreground">{scope==='latest'?'Most recent completed result per case across this Run.':'Results from the selected round only.'} Group totals include passing cases, even with Problems only enabled.</p>
 {!!groups.length&&<div className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>{titles[effectiveField]||effectiveField}</TableHead><TableHead>Cases</TableHead>{['passed','failed','blocked','error','cancelled','pending','running'].filter(status=>groups.some(g=>g.counts[status])).map(status=><TableHead key={status}><Outcome status={status}/></TableHead>)}</TableRow></TableHeader><TableBody>{groups.map(g=><TableRow key={g.key} data-state={chosen?.key===g.key?'selected':undefined} tabIndex={0} className="cursor-pointer" aria-label={'Group '+g.key} onClick={()=>setSelectedGroup(old=>old===g.key?null:g.key)} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setSelectedGroup(old=>old===g.key?null:g.key);}}}><TableCell><Badge variant="secondary">{label(effectiveField,g.key)}</Badge></TableCell><TableCell>{g.total}</TableCell>{['passed','failed','blocked','error','cancelled','pending','running'].filter(status=>groups.some(x=>x.counts[status])).map(status=><TableCell key={status}>{g.counts[status]||'—'}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
 {results.some(c=>Array.isArray(c.meta?.[effectiveField]))&&<p className="text-xs text-muted-foreground">Cases with multiple values appear in each matching group; group totals may overlap.</p>}
 {chosen&&<div className="flex items-center gap-3"><Badge variant="secondary">{label(effectiveField,chosen.key)}</Badge><Button variant="ghost" size="sm" onClick={()=>setSelectedGroup(null)}>Show all groups</Button></div>}

 {!rows.length?<Empty><EmptyHeader><EmptyTitle>No problems found</EmptyTitle><EmptyDescription>No non-passing results in this selection.</EmptyDescription></EmptyHeader></Empty>:<div className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead className="pl-5">Case</TableHead><TableHead>Outcome</TableHead><TableHead>Duration</TableHead><TableHead>Assertions</TableHead><TableHead>Failure / Exclusion reason</TableHead><TableHead className="text-right pr-5">Script</TableHead></TableRow></TableHeader><TableBody>{rows.map(c=><TableRow key={c.id} tabIndex={0} aria-label={c.name} className="cursor-pointer" onClick={()=>setItem(c)} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setItem(c);}}}><TableCell className="max-w-xs whitespace-normal pl-5 font-medium">{c.name}</TableCell><TableCell><Outcome status={c.status||'pending'}/></TableCell><TableCell className="tabular-nums">{duration(c.durationMs)}</TableCell><TableCell>{c.assertions?.length?`${c.assertions.filter(a=>a.passed).length} / ${c.assertions.length}`:'—'}</TableCell><TableCell className="max-w-xs whitespace-normal text-muted-foreground">{c.error||(c.status==='excluded'?selectionReason(c.reason):'—')}</TableCell><TableCell className="text-right pr-5"><ScriptLink id={c.id}/></TableCell></TableRow>)}</TableBody></Table></div>}
 </>}</section><>{rerun&&id&&<RunRegression runId={id} initialMeta={{status:['trial','active']}} onClose={()=>setRerun(false)} onRun={()=>{setRerun(false);if(id)onSelect(id);setRevision(v=>v+1);}}/>}</><CaseSheet item={item} result onClose={()=>setItem(null)}/></div>;
}
