import {groupResults} from '../../../../regression_test/record_store/grouping.mjs';
import {Filter} from './cases';
import {RunRegression} from './run-regression';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {Textarea} from '@/components/ui/textarea';
import {Fragment,useEffect,useState} from 'react';import {ChevronDown,ChevronRight,Copy,Check,StopCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Switch} from '@/components/ui/switch';import {Field,FieldLabel} from '@/components/ui/field';import {Skeleton} from '@/components/ui/skeleton';
import {SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Badge} from '@/components/ui/badge';import {ScrollArea} from '@/components/ui/scroll-area';
import {api,Regression,TestCase,duration,label} from '@/lib/api';import {Outcome,CaseSheet,ScriptLink,ErrorNotice} from './shared';
const date=(s:string)=>new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'medium'}).format(new Date(s));
export function Records({initialId,initialRound,onSelect}:{initialId:string|null;initialRound:string|null;onSelect:(id:string,round?:string)=>void}){
 const prefs=new URL(window.location.hash.slice(1)||'/records','http://trace.local').searchParams;
 const scope='latest';
 const [groupBy,setGroupBy]=useState(prefs.get('groupBy')||'module'),[depth,setDepth]=useState(prefs.get('moduleDepth')||'1'),[expanded,setExpanded]=useState<Set<string>>(()=>new Set());
 const [rerun,setRerun]=useState(false),[revision,setRevision]=useState(0);
 const [latest,setLatest]=useState<any>(null);
 const [history,setHistory]=useState<Regression[]>([]),[prompt,setPrompt]=useState(''),[copied,setCopied]=useState(false);
 const [list,setList]=useState<any[]|null>(null),[id,setId]=useState<string|null>(initialId),[run,setRun]=useState<Regression|null>(null),[item,setItem]=useState<TestCase|null>(null),[problems,setProblems]=useState(false),[error,setError]=useState<string|null>(null),[cancelling,setCancelling]=useState(false);
 useEffect(()=>{let valid=true;api('records').then(v=>{if(valid){setList(v);setId(old=>old||v[0]?.id||null);if(!initialId&&v[0])onSelect(v[0].id);}}).catch(e=>setError(e.message));return()=>{valid=false;};},[]);
 useEffect(()=>{if(initialId)setId(initialId);},[initialId]);
 useEffect(()=>{if(!id)return;let valid=true,timer:ReturnType<typeof setTimeout>;setRun(null);setError(null);setPrompt('');async function load(){try{const group=await api<any>('run_record',{id});if(!valid)return;const r=group.rounds.at(-1);setHistory(group.rounds);setLatest(group);setRun({...r,name:group.name});setList(old=>old?.map(x=>x.id===id?{...x,durationMs:group.rounds.reduce((sum:number,x:Regression)=>sum+(x.durationMs||0),0)}:x)||null);void api<any>('ask_agent',{id}).then(v=>{if(valid)setPrompt(v.prompt);}).catch(e=>{if(valid)setError(e.message);});if(r.state==='running')timer=setTimeout(load,1000);}catch(e:any){if(valid)setError(e.message);}}load();return()=>{valid=false;clearTimeout(timer);};},[id,revision]);
 useEffect(()=>{if(!history.length||latest?.id!==id)return;const selected=history.at(-1)!;setRun({...selected,name:latest.name});setItem(null);},[history,initialRound,id,latest]);

 const results:TestCase[]=scope==='latest'?(latest?.cases||[]):(run?.cases||[]).filter(c=>c.status!=='excluded');
 const fields=[...new Set(results.flatMap(c=>Object.keys(c.meta||{})))].filter(k=>!['id','statusReason'].includes(k)).sort();
 const titles:Record<string,string>={module:'Module',priority:'Priority',surface:'Entry',origin:'Added for',status:'Maturity',effects:'Effects',cost:'Duration class',covers:'Coverage',requires:'Prerequisites',affectedPaths:'Affected paths',suite:'Suite',testLevel:'Test level'};
 const effectiveField=fields.includes(groupBy)?groupBy:fields[0];
 const groups=effectiveField?groupResults(results,effectiveField,{moduleDepth:effectiveField==='module'&&depth!=='all'?Number(depth):undefined}):[];
 function toggleGroup(key:string){setExpanded(old=>{const next=new Set(old);if(next.has(key))next.delete(key);else next.add(key);return next;});}
 useEffect(()=>{const update=()=>{const u=new URL(window.location.hash.slice(1)||'/records','http://trace.local');if(!u.pathname.startsWith('/records'))return;setGroupBy(u.searchParams.get('groupBy')||'module');setDepth(u.searchParams.get('moduleDepth')||'1');};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);

 useEffect(()=>setExpanded(new Set()),[id,scope,groupBy,depth,initialRound]);
 useEffect(()=>{const u=new URL(window.location.hash.slice(1)||'/records','http://trace.local');u.searchParams.set('groupBy',groupBy);u.searchParams.set('moduleDepth',depth);u.searchParams.delete('results');u.searchParams.delete('round');window.history.replaceState(null,'','#'+u.pathname+u.search);},[scope,groupBy,depth,id,initialRound]);

 return <div className="flex h-full min-h-0 overflow-hidden"><aside aria-label="Regression history" className="flex h-full min-h-0 w-64 shrink-0 flex-col border-r bg-sidebar"><h2 className="shrink-0 px-5 pt-6 pb-4 text-xs font-medium text-muted-foreground">Regression history</h2><ScrollArea type="always" className="min-h-0 flex-1 px-3 pb-6">{!list?<Skeleton className="h-32 w-full"/>:<SidebarMenu>{list.map(r=><SidebarMenuItem key={r.id}><SidebarMenuButton size="lg" isActive={r.id===id} onClick={()=>{setItem(null);setId(r.id);onSelect(r.id);}} className="h-auto py-3"><div className="flex min-w-0 flex-col gap-1"><span className="truncate">{/^\d{4}-\d{2}-\d{2}T/.test(r.name)?date(r.startedAt)+' · '+r.name.split(' · ').at(-1):r.name}</span><span className="text-xs text-muted-foreground">{duration(r.durationMs)} · {r.roundCount||1} {(r.roundCount||1)===1?'round':'rounds'}</span></div></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>}</ScrollArea></aside>
 <section className="flex min-h-0 min-w-0 flex-1 flex-col gap-6 overflow-y-auto p-8 [&>*]:shrink-0"><ErrorNotice error={error}/>{!list?<Skeleton className="h-48 w-full"/>:!id?<Empty><EmptyHeader><EmptyTitle>No regression records</EmptyTitle><EmptyDescription>Run selected test cases to create a record.</EmptyDescription></EmptyHeader></Empty>:!run?<Skeleton className="h-48 w-full"/>:<><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{/^\d{4}-\d{2}-\d{2}T/.test(run.name)?'Regression':run.name}</h1><p className="mt-2 text-sm text-muted-foreground">{date(run.startedAt)}</p></div><Button variant="secondary" onClick={()=>setRerun(true)} disabled={history.some(r=>r.state==='running')}>New round</Button><Popover><PopoverTrigger asChild><Button variant="outline">Ask Agent</Button></PopoverTrigger><PopoverContent align="end" className="w-[min(36rem,calc(100vw-2rem))] space-y-3"><p className="text-sm">Copy to your agent and add your question.</p><Textarea readOnly aria-label="Ask Agent instructions" value={prompt} className="min-h-40 font-mono text-xs"/><Button size="sm" onClick={async()=>{try{await navigator.clipboard.writeText(prompt);setCopied(true);}catch(e:any){setError(e.message);}}}>{copied?<Check/>:<Copy/>}{copied?'Copied':'Copy'}</Button></PopoverContent></Popover>{run.state==='running'&&<Button variant="outline" disabled={cancelling} onClick={async()=>{setCancelling(true);try{await api('cancel',{id:run.id},true);}catch(e:any){setError(e.message);}finally{setCancelling(false);}}}><StopCircle data-icon="inline-start"/>Cancel run</Button>}</div>
 <dl className="grid grid-cols-2 gap-6 border-b pb-6 lg:grid-cols-4">{[[scope==='latest'?'Latest status':'Round status',run.state[0].toUpperCase()+run.state.slice(1)],[scope==='latest'?'Run time':'Round time',duration(scope==='latest'?history.reduce((sum,r)=>sum+(r.durationMs||0),0):run.durationMs)],[scope==='latest'?'Result scope':'Round scope',scope==='latest'?'Latest per case across rounds':run.filters?.validateInactive?'Case validation':run.filters?.ids||run.filters?.meta?.id?'Selected cases':run.filters?.surface||run.filters?.meta?.surface?'Selected entry type':run.filters?.meta&&Object.keys(run.filters.meta).some(k=>k!=='status')?'Metadata selection':run.profile==='full'?'Full regression':'Release checks'],['Browser',!run.cases.some(c=>c.meta.surface==='gui'&&c.status!=='excluded')?'Not used':run.environment.browserMode==='device'?'Chrome · CDP':'Headless Chromium']].map(([title,text])=><div key={title}><dt className="text-xs text-muted-foreground">{title}</dt><dd className="mt-2 text-sm font-medium">{(title==='Round status'||title==='Latest status')?<Outcome status={run.state==='completed'?results.some(c=>['failed','error'].includes(c.status||''))?'failed':results.some(c=>c.status==='blocked')?'blocked':results.some(c=>c.status==='cancelled')?'cancelled':results.some(c=>c.status==='passed')?'passed':'excluded':run.state}/>:<Badge variant="secondary">{text}</Badge>}</dd></div>)}</dl>
 <div className="flex flex-wrap items-center gap-6"><Filter id="result-group" title="Group by" value={effectiveField||groupBy} onChange={setGroupBy} options={fields.map(k=>[k,titles[k]||k])}/>{effectiveField==='module'&&<Filter id="result-depth" title="Module depth" value={depth} onChange={setDepth} options={[["1","Level 1"],["2","Level 2"],["3","Level 3"],["all","Full path"]]}/>}<Field orientation="horizontal" className="w-auto"><Switch id="problems" checked={problems} onCheckedChange={setProblems}/><FieldLabel htmlFor="problems">Problems only</FieldLabel></Field></div>
 <p className="text-sm text-muted-foreground">{scope==='latest'?'Latest and each round are shown side by side.':'Results from the selected round only.'} Group totals include passing cases, even with Problems only enabled.</p>
 {results.some(c=>Array.isArray(c.meta?.[effectiveField]))&&<p className="text-xs text-muted-foreground">Cases with multiple values appear in each matching group; group totals may overlap.</p>}
 {!groups.length?<Empty><EmptyHeader><EmptyTitle>No recorded results</EmptyTitle><EmptyDescription>No results are available for this Run.</EmptyDescription></EmptyHeader></Empty>:<div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead className="sticky left-0 min-w-80 bg-background pl-5">Case</TableHead><TableHead className="min-w-48">Latest</TableHead>{history.map((r,i)=><TableHead key={r.id} className="min-w-48">Round {r.roundNumber||i+1}</TableHead>)}<TableHead className="text-right pr-5">Script</TableHead></TableRow></TableHeader><TableBody>{groups.map(g=>{
 const open=expanded.has(g.key),children=g.cases.filter(c=>!problems||c.status!=='passed'),name=label(effectiveField,g.key),ids=new Set(g.cases.map(c=>c.id));
 function summary(cases:TestCase[]){if(!cases.length)return <span className="text-muted-foreground">—</span>;const counts:Record<string,number>={};for(const c of cases)counts[c.status||'pending']=(counts[c.status||'pending']||0)+1;return <div className="flex flex-col items-start gap-2"><Badge variant="secondary">{cases.length} cases</Badge><div className="flex flex-wrap gap-2">{Object.entries(counts).map(([status,count])=><span key={status} className="flex items-center gap-1 text-xs tabular-nums">{count}<Outcome status={status}/></span>)}</div></div>;}
 function cell(c?:TestCase){return c?<button className="flex cursor-pointer flex-col items-start gap-1 text-left" aria-label={c.name+' result '+(c as any).roundNumber} onClick={()=>setItem(c)}><Outcome status={c.status||'pending'}/><span className="text-xs text-muted-foreground">Assertions: {c.assertions?.length?`${c.assertions.filter(a=>a.passed).length} / ${c.assertions.length}`:'—'}</span>{c.error&&<span className="max-w-56 truncate text-xs text-muted-foreground" title={c.error}>{c.error}</span>}</button>:<span className="text-muted-foreground">—</span>;}
 return <Fragment key={g.key}><TableRow className="bg-muted/30"><TableCell className="sticky left-0 bg-background px-3 py-3"><Button variant="ghost" size="sm" aria-label={(open?'Collapse ':'Expand ')+name+' group'} aria-expanded={open} onClick={()=>toggleGroup(g.key)}>{open?<ChevronDown data-icon="inline-start"/>:<ChevronRight data-icon="inline-start"/>}<span>{name}</span></Button></TableCell><TableCell>{summary(g.cases)}</TableCell>{history.map(r=><TableCell key={r.id}>{summary(r.cases.filter(c=>ids.has(c.id)&&c.status!=='excluded'))}</TableCell>)}<TableCell/></TableRow>
 {open&&children.map(c=><TableRow key={c.id} aria-label={c.name}><TableCell className="sticky left-0 max-w-80 whitespace-normal bg-background pl-12 font-medium">{c.name}</TableCell><TableCell>{cell(c)}</TableCell>{history.map(r=><TableCell key={r.id}>{cell(r.cases.find(x=>x.id===c.id&&x.status!=='excluded'))}</TableCell>)}<TableCell className="text-right pr-5"><ScriptLink id={c.id}/></TableCell></TableRow>)}
 {open&&!children.length&&<TableRow><TableCell colSpan={history.length+3} className="pl-12 text-muted-foreground">No current problems in this group.</TableCell></TableRow>}</Fragment>;
 })}</TableBody></Table></div>}


 </>}</section><>{rerun&&id&&<RunRegression runId={id} initialMeta={{status:['trial','active']}} onClose={()=>setRerun(false)} onRun={()=>{setRerun(false);if(id)onSelect(id);setRevision(v=>v+1);}}/>}</><CaseSheet item={item} result onClose={()=>setItem(null)}/></div>;
}
