import {useState,useId} from 'react';import {FileCode2,Copy,Check} from 'lucide-react';
import hljs from 'highlight.js/lib/core';import javascript from 'highlight.js/lib/languages/javascript';
import {Switch} from '@/components/ui/switch';import {Field,FieldLabel} from '@/components/ui/field';
import {Button} from '@/components/ui/button';import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';import {Skeleton} from '@/components/ui/skeleton';import {Alert,AlertTitle,AlertDescription} from '@/components/ui/alert';import {api} from '@/lib/api';
hljs.registerLanguage('javascript',javascript);
export function ScriptLink({id,caseOnly=false}:{id:string;caseOnly?:boolean}){
 const wrapId=useId();const [wrap,setWrap]=useState(false);
 const [open,setOpen]=useState(false),[source,setSource]=useState<{absolutePath:string;content:string}|null>(null),[error,setError]=useState<string|null>(null),[copied,setCopied]=useState(false);
 async function show(){setOpen(true);setSource(null);setError(null);setCopied(false);try{setSource(await api('case_source',{id}));}catch(e:any){setError(e.message);}}
 async function copy(){try{await navigator.clipboard.writeText(source!.absolutePath);setCopied(true);}catch{setError('Unable to copy the file path. Select the path to copy it manually.');}}
 return <><Button variant="ghost" size="sm" onClick={e=>{e.stopPropagation();void show();}}><FileCode2 data-icon="inline-start"/>{caseOnly?'View case file':'View script'}</Button><Sheet open={open} onOpenChange={setOpen}><SheetContent onClick={e=>e.stopPropagation()} className="flex w-full flex-col sm:max-w-4xl"><SheetHeader><SheetTitle>{caseOnly?'Test case file':'Test script'}</SheetTitle><SheetDescription>Current source file in the target repository.</SheetDescription></SheetHeader><div className="flex min-h-0 flex-1 flex-col gap-4 px-6 pb-6">{error&&<Alert variant="destructive"><AlertTitle>Unable to complete the request</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{!source&&!error?<Skeleton className="h-64 w-full"/>:source&&<><div className="flex items-center gap-2 rounded-md border px-3 py-2"><code className="min-w-0 flex-1 break-all text-xs text-muted-foreground">{source.absolutePath}</code><Button variant="ghost" size="icon" aria-label={copied?'File path copied':'Copy file path'} onClick={copy}>{copied?<Check className="text-success"/>:<Copy/>}</Button></div><Field orientation="horizontal" className="w-auto"><Switch id={wrapId} checked={wrap} onCheckedChange={setWrap}/><FieldLabel htmlFor={wrapId}>Wrap lines</FieldLabel></Field><pre className={"min-h-0 flex-1 overflow-auto rounded-md border bg-muted/30 p-4 text-xs leading-6 "+(wrap?"whitespace-pre-wrap [overflow-wrap:anywhere]":"whitespace-pre")}><code className="hljs language-javascript" dangerouslySetInnerHTML={{__html:hljs.highlight(source.content,{language:'javascript'}).value}}/></pre></>}</div></SheetContent></Sheet></>;
}
