import metadata from '../../package.json';
import {App} from '@modelcontextprotocol/ext-apps';
const host=window.parent!==window;const app=host?new App({name:'Trace',version:metadata.version}):null;let catalog;
const status=document.querySelector('#status'),detail=document.querySelector('#detail');
async function call(action,args={}){if(app){const r=await app.callServerTool({name:'trace_'+action,arguments:args});if(r.isError)throw Error(r.content?.[0]?.text||'Tool failed');return r.structuredContent?.data||JSON.parse(r.content[0].text);}const r=await fetch('/api/'+action+'?'+new URLSearchParams(args),{method:action==='upgrade'?'POST':'GET'});const v=await r.json();if(!r.ok)throw Error(v.error);return v.data;}
function display(v){detail.replaceChildren();const text=value=>{const p=document.createElement('p');p.textContent=value;detail.append(p);};const link=(label,url)=>{if(!url)return;const a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noreferrer';detail.append(a,document.createElement('br'));};if(v.executions){if(v.scope)text('性能样本：'+v.count+' 次 · p50 '+v.p50Ms+' ms · p95 '+v.p95Ms+' ms。最多 100 条，不代表全量统计。');for(const e of v.executions){text(e.rootTraceName+' · '+e.durationMs+' ms · '+e.traceID);link('Grafana 详情',e.grafanaUrl);const b=document.createElement('button');b.textContent='展开 Span 链';b.onclick=async()=>{try{display(await call('trace',{id:e.traceID}));}catch(e){status.textContent=e.message;}};detail.append(b);}if(!v.executions.length)text('所选时间范围没有匹配记录');}else if(v.spans){link('Grafana 详情',v.grafanaUrl);for(const s of v.spans){text(s.service+' · '+s.name+' · '+s.durationMs.toFixed(2)+' ms');text('span '+s.id+' ← '+(s.parentId||'root'));const file=s.attributes['code.file.path'];text(file?file+' · '+(s.attributes['code.function.name']||''):'此历史 span 未记录源码位置');}}else if(v.entry){text(v.description);text(v.entry.kind==='command'?[v.entry.executable,...v.entry.args].join(' '):'页面 '+v.entry.page+' · 控件 '+v.entry.target);if(v.url)link('定位实际 GUI 并呼吸高亮',v.url);}else if(v.path){text(v.path+' · '+(v.function||''));text(v.exists?'源码文件存在':'源码文件不存在');}else text(JSON.stringify(v,null,2));}
function render(){if(!catalog)return;document.querySelector('#title').textContent=catalog.project.id+' · Trace';const list=document.querySelector('#entries');list.replaceChildren();const q=document.querySelector('#filter').value.toLowerCase();for(const o of catalog.operations.filter(o=>(o.id+' '+o.description).toLowerCase().includes(q))){const card=document.createElement('article');const id=document.createElement('code');id.textContent=o.id;card.append(id);const p=document.createElement('p');p.textContent=o.description;card.append(p);const state=document.createElement('p');state.textContent=(o.status||'candidate')+' · '+o.owner;card.append(state);for(const [label,action] of [['入口 / 命令','locate'],['源码','source'],['最近 Trace','executions'],['性能样本','performance']]){const b=document.createElement('button');b.textContent=label;b.onclick=async()=>{try{status.textContent='查询中';const v=await call(action,{operation:o.id});display(v);if(action==='locate'&&v.url){if(app)await app.openLink({url:v.url});else window.open(v.url,'_blank','noopener');}status.textContent='已返回';}catch(e){status.textContent=e.message;}};card.append(b);}list.append(card);}}
document.querySelector('#filter').oninput=render;
if(app){app.ontoolresult=r=>{if(r.structuredContent?.action==='operations'){catalog=r.structuredContent.data;render();}else if(r.structuredContent)display(r.structuredContent.data);};await app.connect();}
try{catalog=await call('operations');render();}catch(e){status.textContent=e.message;}

const version=document.querySelector('#version'),upgradeButton=document.querySelector('#upgrade'),upgradeState=document.querySelector('#upgrade-state');
version.textContent='当前 '+metadata.version;
const checkLatest=async()=>{try{version.textContent='检测中';const v=await call('release_check');version.textContent='当前 '+v.installedVersion+' · 最新 '+v.latestVersion+(v.updateAvailable?' · 有更新':' · 已是最新');upgradeButton.disabled=!v.updateAvailable;}catch(e){version.textContent='检测失败：'+e.message;}};
document.querySelector('#check-version').onclick=checkLatest;
void checkLatest();
upgradeButton.onclick=async()=>{try{upgradeButton.disabled=true;await call('upgrade');upgradeState.textContent='正在下载、验证和安装；当前页面可继续使用';const timer=setInterval(async()=>{try{const v=await call('upgrade_status');if(v.state==='running')return;clearInterval(timer);upgradeState.textContent=v.state==='succeeded'?'升级完成：'+v.version+'；请重连 MCP 或重新打开 App':v.error||v.state;}catch(e){clearInterval(timer);upgradeState.textContent=e.message;}},1000);}catch(e){upgradeState.textContent=e.message;}};
