import {readRoute,routeHash} from './lib/route';
import {api} from './lib/api';
import React,{useState,useEffect} from 'react';import {createRoot} from 'react-dom/client';import {Activity,ListChecks,History,Workflow} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarGroup,SidebarGroupContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';import {Separator} from '@/components/ui/separator';import {TooltipProvider} from '@/components/ui/tooltip';
import {Performance} from './features/performance';
import {Cases} from './features/cases';import {Records} from './features/records';import './index.css';
const destinations=[{id:'monitoring',name:'Performance registry',icon:Activity},{id:'cases',name:'Test cases',icon:ListChecks},{id:'records',name:'Regression records',icon:History}];
function WorkspaceNav({page,setPage}:{page:string;setPage:(s:string)=>void}){const {setOpenMobile}=useSidebar();return <Sidebar collapsible="offcanvas"><SidebarHeader className="h-16 justify-center border-b px-5"><div className="flex items-center gap-3"><Workflow className="size-5"/><span className="font-semibold">Agent Dev</span></div></SidebarHeader><SidebarContent><SidebarGroup className="pt-5"><SidebarGroupContent><SidebarMenu>{destinations.map(d=><SidebarMenuItem key={d.id}><SidebarMenuButton isActive={page===d.id} onClick={()=>{setPage(d.id);setOpenMobile(false);}}><d.icon/><span>{d.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent></Sidebar>;}
function App(){const [route,setRoute]=useState(()=>readRoute(window.location.hash)),[config,setConfig]=useState<any>(null);const page=route.page;function navigate(page:string,id?:string|null,round?:string|null){const hash=routeHash(page,id,round);const u=new URL(hash.slice(1),'http://trace.local');if(page==='records'&&route.page==='records'){const current=new URL(window.location.hash.slice(1),'http://trace.local');for(const key of ['groupBy','moduleDepth','results']){const value=current.searchParams.get(key);if(value)u.searchParams.set(key,value);}}window.location.hash='#'+u.pathname+u.search;}const setPage=(page:string)=>navigate(page);useEffect(()=>{const update=()=>setRoute(readRoute(window.location.hash));window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);useEffect(()=>{api('workspace').then(setConfig);},[]);return <TooltipProvider><SidebarProvider style={{'--sidebar-width':'15rem'} as React.CSSProperties}><WorkspaceNav page={page} setPage={setPage}/><SidebarInset className="h-screen min-w-0 overflow-hidden"><header className="flex h-16 shrink-0 items-center gap-4 border-b px-6"><SidebarTrigger/><Separator orientation="vertical" className="h-4"/><span className="text-sm font-medium">{destinations.find(d=>d.id===page)?.name}</span><span className="ml-auto text-sm text-muted-foreground">{config?.project}</span></header><main className="min-h-0 flex-1 overflow-auto">{page==='cases'&&!config?.regressionEnabled?<div className="p-8">Register test cases in regression_test/regression.config.yaml to get started.</div>:page==='records'&&!config?.regressionEnabled?<div className="p-8">No regression configuration found.</div>:page==='cases'?<Cases onRun={id=>{navigate('records',id);}}/>:page==='records'?<Records initialId={route.id} initialRound={route.round} onSelect={(id,round)=>navigate("records",id,round)}/>:config?.performanceEnabled?<Performance initialId={route.id} onSelect={id=>navigate("monitoring",id)}/>:<div className="p-8">No performance registry configured</div>}</main></SidebarInset></SidebarProvider></TooltipProvider>;}
createRoot(document.getElementById('root')!).render(<App/>);
