import {api} from './lib/api';
import React,{useState,useEffect} from 'react';import {createRoot} from 'react-dom/client';import {Activity,ListChecks,History,Workflow} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarGroup,SidebarGroupContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';import {Separator} from '@/components/ui/separator';import {TooltipProvider} from '@/components/ui/tooltip';
import {Performance} from './features/performance';
import {Cases} from './features/cases';import {Records} from './features/records';import './index.css';
const destinations=[{id:'monitoring',name:'Performance registry',icon:Activity},{id:'cases',name:'Test cases',icon:ListChecks},{id:'records',name:'Regression records',icon:History}];
function WorkspaceNav({page,setPage}:{page:string;setPage:(s:string)=>void}){const {setOpenMobile}=useSidebar();return <Sidebar collapsible="offcanvas"><SidebarHeader className="h-16 justify-center border-b px-5"><div className="flex items-center gap-3"><Workflow className="size-5"/><span className="font-semibold">Agent DevOps</span></div></SidebarHeader><SidebarContent><SidebarGroup className="pt-5"><SidebarGroupContent><SidebarMenu>{destinations.map(d=><SidebarMenuItem key={d.id}><SidebarMenuButton isActive={page===d.id} onClick={()=>{setPage(d.id);setOpenMobile(false);}}><d.icon/><span>{d.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent></Sidebar>;}
function App(){const [page,setPage]=useState('monitoring'),[config,setConfig]=useState<any>(null),[runId,setRunId]=useState<string|null>(null);useEffect(()=>{api('workspace').then(setConfig);},[]);return <TooltipProvider><SidebarProvider style={{'--sidebar-width':'15rem'} as React.CSSProperties}><WorkspaceNav page={page} setPage={setPage}/><SidebarInset className="h-screen min-w-0 overflow-hidden"><header className="flex h-16 shrink-0 items-center gap-4 border-b px-6"><SidebarTrigger/><Separator orientation="vertical" className="h-4"/><span className="text-sm font-medium">{destinations.find(d=>d.id===page)?.name}</span><span className="ml-auto text-sm text-muted-foreground">{config?.project}</span></header><main className="min-h-0 flex-1 overflow-auto">{page==='cases'&&!config?.regressionEnabled?<div className="p-8">Register test cases in regression_test/regression.config.yaml to get started.</div>:page==='records'&&!config?.regressionEnabled?<div className="p-8">No regression configuration found.</div>:page==='cases'?<Cases onRun={id=>{setRunId(id);setPage('records');}}/>:page==='records'?<Records initialId={runId}/>:config?.performanceEnabled?<Performance/>:<div className="p-8">No performance registry configured</div>}</main></SidebarInset></SidebarProvider></TooltipProvider>;}
createRoot(document.getElementById('root')!).render(<App/>);
