#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const npm=process.platform==='win32'?'npm.cmd':'npm';
function run(command,args,cwd=root){const result=spawnSync(command,args,{cwd,stdio:'inherit'});if(result.error)throw result.error;if(result.status!==0)throw Error(`${command} exited ${result.status}`);}
function fingerprint(dir){return crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,'npm-shrinkwrap.json'))).digest('hex');}
function check(){const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'))),state=path.join(root,'.setup/state.json');let receipt=null;try{receipt=JSON.parse(fs.readFileSync(state));}catch{}
const runtimeOK=Number(process.versions.node.split('.')[0])>=20;
const dependencies=['@modelcontextprotocol/sdk','@modelcontextprotocol/ext-apps','yaml','zod','esbuild'].every(p=>fs.existsSync(path.join(root,'node_modules',p,'package.json')));
const built=['view.bundle.js','mcp.html'].every(f=>fs.existsSync(path.join(root,'catalog/frontend',f)));
return {version:pkg.version,node:process.versions.node,runtimeOK,dependencies,built,lockMatches:receipt?.lockDigest===fingerprint(root),ready:runtimeOK&&dependencies&&built&&receipt?.lockDigest===fingerprint(root)};}
function install(dir=root){if(Number(process.versions.node.split('.')[0])<20)throw Error('Node.js >=20 required; install from the official Node.js distribution or your package manager');run(npm,['ci','--ignore-scripts','--include=dev'],dir);run(npm,['run','build'],dir);fs.mkdirSync(path.join(dir,'.setup'),{recursive:true});fs.writeFileSync(path.join(dir,'.setup/state.json'),JSON.stringify({version:JSON.parse(fs.readFileSync(path.join(dir,'package.json'))).version,lockDigest:fingerprint(dir),installedAt:new Date().toISOString()},null,2));}
// Distribution is defined by npm's package file allowlist, not by recursively copying an installation.
function files(dir){const r=spawnSync(npm,['pack','--dry-run','--json','--ignore-scripts'],{cwd:dir,encoding:'utf8'});if(r.status!==0)throw Error('Cannot enumerate source package');return JSON.parse(r.stdout)[0].files.map(f=>f.path).filter(p=>!p.endsWith('.tgz'));}
function update(source){source=fs.realpathSync(source);if(source===fs.realpathSync(root))throw Error('Update source must be a separate source directory');const manifest=JSON.parse(fs.readFileSync(path.join(source,'package.json')));if(manifest.name!=='@personal/trace')throw Error('Not a trace source package');const stage=fs.mkdtempSync(path.join(os.tmpdir(),'trace-update-'));const selected=files(source);try{for(const file of selected){const from=path.resolve(source,file);if(!from.startsWith(source+path.sep)||!fs.realpathSync(from).startsWith(source+path.sep))throw Error('Unsafe package path');const to=path.join(stage,file);fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(from,to);}install(stage);run(npm,['test'],stage);
const backup=path.join(root,'.setup/backups',new Date().toISOString().replace(/[:.]/g,'-'));fs.mkdirSync(backup,{recursive:true});const previous=files(root);const managed=new Set([...previous,...selected]);for(const file of managed){const old=path.join(root,file);if(fs.existsSync(old)){const save=path.join(backup,file);fs.mkdirSync(path.dirname(save),{recursive:true});fs.copyFileSync(old,save);}}
try{for(const file of managed){const from=path.join(stage,file),to=path.join(root,file);if(fs.existsSync(from)){fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(from,to);}else if(fs.existsSync(to))fs.unlinkSync(to);}install(root);}catch(error){for(const file of managed){const saved=path.join(backup,file),to=path.join(root,file);if(fs.existsSync(saved)){fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(saved,to);}else if(fs.existsSync(to))fs.unlinkSync(to);}install(root);throw error;}return {version:manifest.version,backup};}finally{fs.rmSync(stage,{recursive:true,force:true});}}
try{const command=process.argv[2]||'check';if(command==='check'){const status=check();console.log(JSON.stringify(status,null,2));if(!status.ready)process.exitCode=1;}else if(command==='install'){install();console.log(JSON.stringify(check(),null,2));}else if(command==='release-check'){const {latest}=await import('./github.mjs');console.log(JSON.stringify(await latest(),null,2));}else if(command==='upgrade'){const {upgrade}=await import('./github.mjs');console.log(JSON.stringify(await upgrade({force:process.argv.includes('--force')}),null,2));}else if(command==='configure'){const {configure}=await import('./configure.mjs');console.log(JSON.stringify(configure(JSON.parse(fs.readFileSync(0,'utf8'))),null,2));}else if(command==='update'){if(process.argv[3]!=='--from'||!process.argv[4])throw Error('Use update --from <trusted-source-directory>');console.log(JSON.stringify(update(process.argv[4]),null,2));}else throw Error('Use check, install or update');}catch(error){console.error(JSON.stringify({ok:false,error:error.message}));process.exitCode=1;}
